### ISSUE TITLE
publish_model does not create astore

### ISSUE THREAD

**Issue by Mentos05** [sassoftware/python-sasctl#16] opened 2019-07-31 19:43 UTC
Hi,

I am trying to use the publish_model function, to publish an astore to MAS which is working fine via Model Manager GUI but does not work via API.
The sashdat is created below /opt/sas/viya/config/data/cas/default/modelStore/
But I don't see any astore file created at /opt/sas/viya/config/data/modelsvr/astore/ (only the one via GUI, I've set 777 for test)

The MAS log says the following:
tail -f /var/log/sas/viya/microanalyticservice/default/LOGFILE-> 
2019-07-31 18:27:18.381  INFO 98363 --- [ask-scheduler-4] MAS_JOB_LOGGER                           : service [93274beffdfa9b89] [JOB_PROCESSED] Job c844770d-90db-4923-97ab-38b8fe8c4491 for module gbtest36 processed with status FAILED.

I tried this with Python 3.6.3, Viya 3.4 and Model Manager 15.2

Attached is my sample code:
[python_code.txt](https://github.com/sassoftware/python-sasctl/files/3453621/python_code.txt)

Am I missing something or is there anything wrong with my versions?

Thank you and best regards!

Michael

**Comment by jlwalke2** [comment] 2019-07-31 19:56
No, I don't think you're doing anything wrong - this is a known issue that I was hoping to have fixed before it was discovered :)

Right now, it looks like the problem is related to copying the ASTORE file:
https://developer.sas.com/apis/rest/DecisionManagement/#copy-analytic-stores-for-a-model-to-a-pre-defined-location

This service appears to return a successful status even though the file is not copied.  MAS then fails to create the module since it can't find the ASTORE in /models/astores/viya (which is generally symlinked to /opt/sas/viya/config/data/modelsrv/astore.

**Comment by Mentos05** [comment] 2019-07-31 20:05
Good to know,
That’s exactly what I thought. 

Do you have any idea when this will be fixed?
And is there any workaround available in the meantime?

Best Regards
Michael


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jlwalke2** [comment] 2019-07-31 20:07
No timeline yet.  I haven't tried it, but manually copying the ASTORE may work in the meantime.

**Comment by jlwalke2** [comment] 2019-10-10 17:41
fixed in v1.2.5

**Closed by jlwalke2** 2019-10-10 17:41 UTC
Labels: bug
