### ISSUE TITLE
Problem with "import_model_from_zip"

### ISSUE THREAD

**Issue by zwyszomi** [sassoftware/python-sasctl#84] opened 2021-01-28 02:35 UTC
[HmeqDecTreev3.zip](https://github.com/sassoftware/python-sasctl/files/5884349/HmeqDecTreev3.zip)

Hi
I'm trying to import Python model into ModelManager using sasctl package.
Attached is my notebook which is based on the example published here.
In the last step when import_model_from_zip is executed I'm getting a syntax like error saying that project parameter is not defined?
I thing my code in this block is 1:1 comparing to the published example. I'd be grateful for advice how to correct my error, please
Regards
Ziggy

**Comment by zwyszomi** [comment] 2021-01-28 04:01
I have checked that when UUID is provided instead of Project name it works.
What is the correct path for the project name or if only name is provided what is the default location searched by sasctl?
Ziggy

**Comment by zwyszomi** [comment] 2021-01-28 10:22
It seems that when MM Project is stored under '/Model Repositories/Public' it works. Is it a hard coded setting or it can be modified somehow?
Ziggy

**Comment by smlindauer** [comment] 2021-01-28 14:02
Hey @zwyszomi,

I believe the issue is caused by an incorrect error message response. It looks like when the project you are attempting to reference (PyTestProject) does not already exist in Model Manager, instead of asking you to create it (or the code calling an API to create it; I'll add that to the proposed features of import_model_from_zip) it returns the

Project 'None' could not be found.

If you create the project with the PyTestProject name ahead of time on MM, then the code should work.

Let me know if that works.

**Comment by zwyszomi** [comment] 2021-01-28 16:19
Hi 
Indeed, it should be referenced the existing MM project. Is there any way to specify the path to the existing MM project. It seems that now only the Public path is being searched?
Ziggy

**Comment by smlindauer** [comment] 2021-01-29 20:56
So I have played around with this a bit and I think the issue may be on the MM side rather than the sasctl side, however I could not recreate the exact case you described on my server.

I tested a number of projects that were not in the Public directory and was able to get successful GET returns from modelRepository/projects/ for each case I tried. I know there have been previous issues with filter handling not working perfectly for some of the API calls. It could be that the filter that [sasctl has defaulted to using](https://github.com/sassoftware/python-sasctl/blob/cc85a02ba4a6a6a7e65f097220737c73bbb2f524/src/sasctl/_services/service.py#L173) is incorrect. 

I will investigate further, since I have also encountered similar filter issues in the past. 

Can you provide me with any further details about the location and set up of your project on your server?

**Comment by smlindauer** [comment] 2022-06-22 16:24
pzmm has moved away from directly calling import_model_from_zip, and now has built in functions (see examples) that check on project existence and status before attempting to import the model. As such, I am closing this bug.

**Closed by smlindauer** 2022-06-22 16:24 UTC
Labels: bug, question
